name: Build and Deploy to Azure Container Instance with Storage

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: getting-started
  CONTAINER_NAME: registryahmed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: az acr login --name ${{ secrets.REGISTRY_USERNAME }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:v1.0 .

    - name: Push image to Azure Container Registry
      run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:v1.0

    - name: Deploy container to Azure Container Instance with persistent storage
      run: |
        az container create \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name ${{ env.CONTAINER_NAME }} \
          --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:v1.0 \
          --registry-login-server ${{ secrets.REGISTRY_LOGIN_SERVER }} \
          --registry-username ${{ secrets.REGISTRY_USERNAME }} \
          --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
          --cpu 1 \
          --memory 1.5 \
          --ports 3000 \
          --os-type Linux \
          --azure-file-volume-account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
          --azure-file-volume-account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} \
          --azure-file-volume-share-name ${{ secrets.FILE_SHARE_NAME }} \
          --azure-file-volume-mount-path ${{ secrets.VOLUME_MOUNT_PATH }} \
          --restart-policy Always \
          --location westeurope
